apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podsense-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /predict/url
            pathType: Prefix
            backend:
              service:
                name: podsense-service
                port:
                  number: 80
