apiVersion: v1
kind: Service
metadata:
  name: PodSense-Service
  namespace: default
spec:
  selector:
    app: PodSense-pods
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      nodePort: 30001
